import java_cup.runtime.*;
 
action code{:Integer ant=0;
             Integer suma=0;:};

terminal Integer NUMERO;

non terminal expList, linea, exp, restoExp;



expList ::= linea expList | linea;

linea ::= NUMERO:a NUMERO:b {:ant = b; suma = a+b;:} restoExp
        | NUMERO:a NUMERO:b {:if(b==2*a){
                                System.out.println("SI");
                            }else{
                                System.out.println("NO");
                            }:};

restoExp ::= NUMERO:a {:if(suma==a){suma=ant+b; ant = a;}else{suma=-1;}:} restoExp
            |NUMERO:a {:if(suma==a){System.out.println("SI");}else{System.out.println("NO");}:};
