
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 13;
  public static final int COMA = 9;
  public static final int SUBSTR = 11;
  public static final int PUNTO = 8;
  public static final int MENOS = 3;
  public static final int CP = 6;
  public static final int EOF = 0;
  public static final int PYC = 7;
  public static final int MAS = 2;
  public static final int NUMERO = 15;
  public static final int ID = 14;
  public static final int IGUAL = 4;
  public static final int error = 1;
  public static final int PRINT = 10;
  public static final int SIZE = 12;
  public static final int AP = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "IGUAL",
  "AP",
  "CP",
  "PYC",
  "PUNTO",
  "COMA",
  "PRINT",
  "SUBSTR",
  "SIZE",
  "CADENA",
  "ID",
  "NUMERO"
  };
}

