
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 3;
  public static final int MENOR = 17;
  public static final int ELSE = 28;
  public static final int Y = 22;
  public static final int CP = 15;
  public static final int PYC = 10;
  public static final int INT = 31;
  public static final int IGUAL = 23;
  public static final int OR = 21;
  public static final int MENORIGUAL = 19;
  public static final int WHILE = 29;
  public static final int MENOSMENOS = 9;
  public static final int CL = 13;
  public static final int IF = 27;
  public static final int POR = 4;
  public static final int AP = 14;
  public static final int NUM = 33;
  public static final int DO = 30;
  public static final int STRING = 32;
  public static final int COMA = 11;
  public static final int AL = 12;
  public static final int DISTINTO = 24;
  public static final int MAYOR = 18;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int MAYORIGUAL = 20;
  public static final int MASMAS = 8;
  public static final int PRINT = 25;
  public static final int error = 1;
  public static final int FOR = 26;
  public static final int ASIG = 6;
  public static final int MAS = 2;
  public static final int NEGADO = 16;
  public static final int UMINUS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ASIG",
  "UMINUS",
  "MASMAS",
  "MENOSMENOS",
  "PYC",
  "COMA",
  "AL",
  "CL",
  "AP",
  "CP",
  "NEGADO",
  "MENOR",
  "MAYOR",
  "MENORIGUAL",
  "MAYORIGUAL",
  "OR",
  "Y",
  "IGUAL",
  "DISTINTO",
  "PRINT",
  "FOR",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "INT",
  "STRING",
  "NUM"
  };
}

